{% set version = '1.3.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-admiraldev
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/admiraldev_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/admiraldev/admiraldev_{{ version }}.tar.gz
  sha256: 4dd3d03078532078e9b2c717ec3d7cbe53e9052fff49af07d639c4b49d09df30

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.0.0
    - r-dplyr >=1.0.5
    - r-glue >=1.6.0
    - r-lifecycle >=0.1.0
    - r-lubridate >=1.7.4
    - r-purrr >=0.3.3
    - r-rlang >=0.4.4
    - r-roxygen2 >=7.0.0
    - r-stringr >=1.4.0
    - r-tidyr >=1.0.2
    - r-tidyselect >=1.0.0
    - r-withr
  run:
    - r-base
    - r-cli >=3.0.0
    - r-dplyr >=1.0.5
    - r-glue >=1.6.0
    - r-lifecycle >=0.1.0
    - r-lubridate >=1.7.4
    - r-purrr >=0.3.3
    - r-rlang >=0.4.4
    - r-roxygen2 >=7.0.0
    - r-stringr >=1.4.0
    - r-tidyr >=1.0.2
    - r-tidyselect >=1.0.0
    - r-withr

test:
  commands:
    - $R -e "library('admiraldev')"           # [not win]
    - "\"%R%\" -e \"library('admiraldev')\""  # [win]

about:
  home: https://pharmaverse.github.io/admiraldev/, https://github.com/pharmaverse/admiraldev/
  license: Apache-2.0
  summary: Utility functions to check data, variables and conditions for functions used in 'admiral'
    and 'admiral' extension packages. Additional utility helper functions to assist
    developers with maintaining documentation, testing and general upkeep of 'admiral'
    and 'admiral' extension packages.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
